apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-k8s-deployment
  namespace: qa
  annotations:
      circleci.com/project-id: ed46f476-40e2-4456-ba81-24827e89e635
  labels:
      circleci.com/component-name: my-k8s-app
      circleci.com/version: 1.0.0
      app: my-k8s-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-k8s-app
  template:
    metadata:
      labels:
        app: my-k8s-app
        circleci.com/component-name: my-k8s-app
        circleci.com/version: 1.0.0
    spec:
      containers:
      - name: my-container
        image: tristan090/my-k8s-app:qa
        imagePullPolicy: Always
        ports:
        - containerPort: 3000